### ISSUE TITLE
Save Inventory Per Gamemode Change

### ISSUE THREAD

**Issue by Bagoschwago** [Enrick3344/PerWorldInventory#2]
This is a great plugin! Thank you for making it.

Would it be possible to make it work on a per gamemode basis? It seems to be just updating the EntityLevelChangeEvent to a PlayerGameModeChangeEvent but I'm not the best at programming. 

If a player is gong from survival worlds to survival worlds inventory stays the same but only when going from creative to survival it prevents it?

**Comment by Enrick3344** [comment]
I will see what I can do! btw we accept help.
